config/routes.rb
Rails.application.routes.draw do
  resources :comments, except: [:edit, :update]
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  include AsConversationEntry

  belongs_to :project
end

app/models/concerns/as_conversation_entry.rb
module AsConversationEntry
  extend ActiveSupport::Concern

  included do
    has_one :conversation_entry, as: :activity,
      touch: true,
      dependent: :destroy
  end
end

app/models/conversation_entry.rb
class ConversationEntry < ApplicationRecord
  belongs_to :project
  delegated_type :activity, types: %w[Comment ProjectStatusChange]

  def self.create_with_activity(activity)
    ConversationEntry.create! \
      activity: activity,
      project_id: activity.project_id
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :status_changes, dependent: :destroy, class_name: "ProjectStatusChange"
  has_many :comments, dependent: :destroy

  enum status: {
    initial: "initial",
    in_progress: "in_progress",
    completed: "completed"
  }
end

app/models/project_status_change.rb
class ProjectStatusChange < ApplicationRecord
  belongs_to :project

  enum :from, Project.statuses, prefix: true
  enum :to, Project.statuses, prefix: true

  def self.create_status_change!(project:, from:, to:)
    ProjectStatusChange.create! \
      project: project,
      from: from,
      to: to
  end
end

app/models/projects/loaders/conversation_entries_loader.rb
module Projects
  module Loaders
    class ConversationEntriesLoader
      def call(project:)
        ConversationEntry.where(project: project)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[show edit update destroy]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    form = CommentForm.new
    render locals: {form: form}
  end

  def create
    form = CommentForm.new(comment_params)
    create_comment = CreateComment.new.call(form: form)

    if create_comment.success?
      comment = create_comment.value!

      redirect_to comment_url(comment), notice: "Comment was successfully created."
    else
      render :new, status: :unprocessable_entity, form: form
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  class CommentForm
    include ActiveModel::Model
    include ActiveModel::Attributes

    attribute :text, :string
    attribute :project_id, :integer
  end

  class CreateComment
    include Dry::Monads[:result]

    def call(form:)
      return Failure(form) unless form.valid?

      comment = Comment.new
      comment.text = form.text
      comment.project_id = form.project_id

      Comment.transaction do
        comment.save!

        ConversationEntry.create_with_activity(comment)
      end

      Success(comment)
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(CommentForm.model_name.param_key).permit(:project_id, :text)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    form = ProjectUpdateForm.new(@project.attributes.slice("name", "status"))

    render locals: {form: form}
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    form = ProjectUpdateForm.new(update_project_params)
    update_project = UpdateProject.new.call(form: form, project: @project)

    if update_project.success?
      project = update_project.value!

      redirect_to project_url(project), notice: "Project was successfully updated."
    else
      render :edit, status: :unprocessable_entity, form: form
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  class ProjectUpdateForm
    include ActiveModel::Model
    include ActiveModel::Attributes

    attribute :name, :string
    attribute :status, :string

    def persisted?
      true
    end
  end

  class UpdateProject
    include Dry::Monads[:result]

    def call(form:, project:)
      return Failure(form) unless form.valid?

      from_status = project.status
      to_status = form.status

      project.name = form.name
      project.status = form.status

      Project.transaction do
        project.save!

        status_change = ProjectStatusChange.create_status_change!(
          project: project,
          from: from_status,
          to: to_status
        )

        ConversationEntry.create_with_activity(status_change)
      end

      Success(project)
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def update_project_params
    params.require(ProjectUpdateForm.model_name.param_key).permit(:name, :status)
  end

  def project_params
    params.require(:project).permit(:name, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Project:</strong>
    <%= comment.project&.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Comment:</strong>
    <%= comment.text %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this comment", comment, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: form, url: comments_path, class: "contents") do |f| %>
  <% if f.object.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(f.object.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% f.object.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= f.label :project_id %>
    <%= f.collection_select :project_id, Project.all, :id, :name, {}, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= f.label :text %>
    <%= f.text_area :text, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= f.submit "Create", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/comments/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Comments</h1>
    <%= link_to 'New comment', new_comment_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="comments" class="min-w-full">
    <%= render @comments %>
  </div>
</div>

app/views/comments/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New comment</h1>

  <%= render "form", form: form %>

  <%= link_to 'Back to comments', comments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/comments/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @comment %>

    <div class="inline-block ml-2">
      <%= button_to 'Destroy this comment', comment_path(@comment), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to comments', comments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/conversation_entries/activities/_comment.html.erb
<% comment = conversation_entry.activity %>

<div id="<%= dom_id conversation_entry %>"  class="bg-gray-100 p-6 rounded-lg">
  <p>
    <%= comment.text %>
  </p>

  <div class="text-xs text-gray-500 mt-8">
    <%= l(comment.created_at, format: :short) %>
  </div>
</div>

app/views/conversation_entries/activities/_project_status_change.html.erb
<% status_change = conversation_entry.activity %>

<div id="<%= dom_id conversation_entry %>" class="bg-gray-700 text-white px-6 py-4 rounded-xl">
  <p>
    <%= status_change.from.titleize %> → <%= status_change.to.titleize %>
  </p>

  <div class="text-xs text-gray-500 mt-4">
    <%= l(status_change.created_at, format: :short) %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeyProjectConversationHistory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="container mx-auto mt-6 flex">
      <%= link_to "Projects", root_path, class: "px-6 py-2" %>
      <%= link_to "Comments", comments_path, class: "px-6 py-2" %>
    </nav>

    <main class="container mx-auto mt-16 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/projects/_form.html.erb
<% url = project.persisted? ? project_path(project) : projects_path %>

<%= form_with(model: form, url: url, class: "contents") do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= f.label :name %>
    <%= f.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <% statuses = Project.statuses.values.map { |s| [s.titleize, s]} %>
    <%= f.label :status %>
    <%= f.select :status, statuses, {}, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <% title = project.persisted? ? "Update" : "Create" %>
    <%= f.submit title, class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= project.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= project.status&.titleize %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this project", project, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this project', edit_project_path(project), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/projects/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing project</h1>

  <%= render "form", form: form, project: @project %>

  <%= link_to "Show this project", @project, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to projects", projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/projects/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Projects</h1>
    <%= link_to 'New project', new_project_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="projects" class="min-w-full">
    <%= render @projects %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New project</h1>

  <%= render "form", form: @project, project: @project %>

  <%= link_to 'Back to projects', projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/projects/show.html.erb
<% project = @project %>

<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div id="<%= dom_id project %>" class="mb-10">
      <h1 class="text-4xl mb-2"><%= project.name %></h1>
      <h1 class="text-xl text-gray-600 mb-6"><%= project.status&.titleize %></h1>

      <div class="flex justify-between items-center">
        <h5 class="font-bold mb-2">Conversation history</h5>
      </div>

      <% conversation_entries = Projects::Loaders::ConversationEntriesLoader.new.call(project: project) %>

      <div id="conversation_entries" class="min-w-full space-y-4">
        <% conversation_entries.each do |conversation_entry| %>
          <%= render "conversation_entries/activities/#{conversation_entry.activity_type.underscore}",
                  conversation_entry: conversation_entry %>
        <% end %>
      </div>
    </div>

    <hr>

    <%= link_to 'Edit this project', edit_project_path(@project), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this project', project_path(@project), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to projects', projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>